Swift 3 support
thefuntasty/Funtasty-CleanSwift-templates pull request #18
Opened 2016-10-18 12:56 UTC by kafejo

2016-10-18 13:06 UTC, jakubknejzlik requested changes

2016-10-18 13:06 UTC, jakubknejzlik commented on Clean Swift/Storyboard Reference.xctemplate/___FILEBASENAME___.swift
> +        if let controller = UIStoryboard(name: S.name, bundle: nil)..instantiateViewController(withIdentifier: id) as? T {
Double dot typo

2016-10-18 13:19 UTC, kafejo commented
Resolved @jakubknejzlik

2016-10-18 14:04 UTC, jakubknejzlik approved these changes

2016-10-21 18:50 UTC, kafejo commented
@mkj-is can you merge it?

2016-10-22 15:57 UTC, mkj-is approved these changes

2016-10-22 15:57 UTC, merged